import { Tutor, Category } from "../types/types";

export const MENTORS: Tutor[] = [
  {
    id: "1",
    name: "Ethan Caldwell",
    role: "Python Developer",
    rating: 4.9,
    reviewCount: 124,
    experience: "20 years of experience",
    hourlyRate: 85,
    imageUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    specialty: "Coding",
    location: "San Francisco, CA",
    about:
      "I am a Senior Python Developer with over 20 years of experience in building scalable web applications and data processing pipelines. Currently working as a Lead Engineer at a major tech firm. I love mentoring aspiring developers and helping them master Python, Django, and System Design.",
    totalMentoringMins: 4500,
    totalSessions: 85,
    responseTime: "2 hrs",
    topPercentile: 1,
    expertise: ["Python", "Django", "System Design", "Cloud Architecture"],
    industries: ["FinTech", "SaaS", "E-commerce"],
    socialLinks: { linkedin: "#", twitter: "#", website: "#" },
  },
  {
    id: "2",
    name: "Adriana Silva",
    role: "UI/UX Designer",
    rating: 5.0,
    reviewCount: 98,
    experience: "15 years of experience",
    hourlyRate: 75,
    imageUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    specialty: "Design",
    location: "Lisbon, Portugal",
    about:
      "Passionate UI/UX Designer creating intuitive and beautiful digital experiences. I specialize in user research, wireframing, and high-fidelity prototyping. I have worked with startups and Fortune 500 companies alike.",
    totalMentoringMins: 3200,
    totalSessions: 60,
    responseTime: "1 hr",
    topPercentile: 5,
    expertise: ["Figma", "User Research", "Prototyping", "Design Systems"],
    industries: ["Consumer Apps", "HealthTech"],
    socialLinks: { linkedin: "#", website: "#" },
  },
  {
    id: "3",
    name: "Marcus Johnson",
    role: "Data Scientist",
    rating: 4.8,
    reviewCount: 76,
    experience: "12 years of experience",
    hourlyRate: 90,
    imageUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    specialty: "Data Science",
    location: "London, UK",
    about:
      "Data Scientist with a background in Applied Mathematics. I help students and professionals understand machine learning algorithms, statistical analysis, and data visualization.",
    totalMentoringMins: 2800,
    totalSessions: 45,
    responseTime: "4 hrs",
    topPercentile: 8,
    expertise: ["Machine Learning", "Python", "SQL", "Tableau"],
    industries: ["Finance", "Consulting"],
    socialLinks: { linkedin: "#", twitter: "#" },
  },
  {
    id: "4",
    name: "Sarah Chen",
    role: "Product Manager",
    rating: 4.7,
    reviewCount: 42,
    experience: "8 years of experience",
    hourlyRate: 110,
    imageUrl:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    specialty: "Business",
    location: "New York, NY",
    about:
      "Product leader with experience scaling SaaS products from 0 to 1M users. Expert in roadmap planning, stakeholder management, and agile methodologies.",
    totalMentoringMins: 1200,
    totalSessions: 25,
    responseTime: "5 hrs",
    topPercentile: 10,
    expertise: ["Product Strategy", "Agile", "User Stories", "Roadmapping"],
    industries: ["SaaS", "EdTech"],
    socialLinks: { linkedin: "#" },
  },
  {
    id: "5",
    name: "Michael Ross",
    role: "Frontend Architect",
    rating: 4.9,
    reviewCount: 205,
    experience: "10 years of experience",
    hourlyRate: 95,
    imageUrl:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    specialty: "Coding",
    location: "Berlin, Germany",
    about:
      "Specializing in React, TypeScript, and modern frontend performance. I help developers transition from junior to senior roles.",
    totalMentoringMins: 6000,
    totalSessions: 150,
    responseTime: "1 hr",
    topPercentile: 2,
    expertise: ["React", "TypeScript", "Next.js", "Performance"],
    industries: ["Tech", "Media"],
    socialLinks: { twitter: "#", website: "#" },
  },
  {
    id: "6",
    name: "Elena Rodriguez",
    role: "Digital Marketer",
    rating: 4.6,
    reviewCount: 33,
    experience: "6 years of experience",
    hourlyRate: 65,
    imageUrl:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    specialty: "Marketing",
    location: "Madrid, Spain",
    about:
      "Helping brands tell their story through social media and content marketing. SEO expert and PPC strategist.",
    totalMentoringMins: 900,
    totalSessions: 18,
    responseTime: "3 hrs",
    topPercentile: 15,
    expertise: ["SEO", "Content Strategy", "Social Media", "Google Ads"],
    industries: ["Retail", "Fashion"],
    socialLinks: { linkedin: "#" },
  },
  {
    id: "7",
    name: "David Kim",
    role: "Cybersecurity Analyst",
    rating: 5.0,
    reviewCount: 15,
    experience: "5 years of experience",
    hourlyRate: 120,
    imageUrl:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    specialty: "Coding",
    location: "Seoul, South Korea",
    about:
      "Certified ethical hacker and security consultant. I teach network security, penetration testing, and security compliance.",
    totalMentoringMins: 600,
    totalSessions: 12,
    responseTime: "24 hrs",
    topPercentile: 20,
    expertise: ["Penetration Testing", "Network Security", "Cryptography"],
    industries: ["Cybersecurity", "Banking"],
    socialLinks: { website: "#" },
  },
  {
    id: "8",
    name: "Olivia Wilson",
    role: "English Tutor",
    rating: 4.8,
    reviewCount: 310,
    experience: "12 years of experience",
    hourlyRate: 40,
    imageUrl:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    specialty: "Language",
    location: "Toronto, Canada",
    about:
      "TEFL certified English teacher specializing in business English and accent reduction for professionals.",
    totalMentoringMins: 12000,
    totalSessions: 400,
    responseTime: "1 hr",
    topPercentile: 3,
    expertise: ["Business English", "Public Speaking", "Writing"],
    industries: ["Education"],
    socialLinks: { linkedin: "#" },
  },
  {
    id: "9",
    name: "James Carter",
    role: "Music Producer",
    rating: 4.9,
    reviewCount: 55,
    experience: "15 years of experience",
    hourlyRate: 100,
    imageUrl:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    specialty: "Music",
    location: "Los Angeles, CA",
    about:
      "Grammy-nominated producer teaching music theory, composition, and production in Logic Pro and Ableton.",
    totalMentoringMins: 1500,
    totalSessions: 30,
    responseTime: "6 hrs",
    topPercentile: 4,
    expertise: ["Music Production", "Mixing", "Mastering", "Logic Pro"],
    industries: ["Music", "Entertainment"],
    socialLinks: { website: "#" },
  },
];

export const TUTORS = MENTORS;

export const CATEGORIES: Category[] = [
  {
    id: "coding",
    name: "Coding",
    iconName: "Code",
    count: 350,
    description: "Master modern programming languages and frameworks.",
    topics: ["Python", "React", "JavaScript", "DevOps"],
  },
  {
    id: "design",
    name: "Design",
    iconName: "PenTool",
    count: 210,
    description: "Learn UI/UX, graphic design, and motion graphics.",
    topics: ["Figma", "Adobe CC", "Prototyping", "User Research"],
  },
  {
    id: "business",
    name: "Business",
    iconName: "Briefcase",
    count: 180,
    description: "Develop leadership, strategy, and entrepreneurial skills.",
    topics: ["Startups", "Management", "Strategy", "Finance"],
  },
  {
    id: "marketing",
    name: "Marketing",
    iconName: "Megaphone",
    count: 145,
    description: "Grow brands with digital marketing and SEO strategies.",
    topics: ["SEO", "Social Media", "Content", "Ads"],
  },
  {
    id: "language",
    name: "Language",
    iconName: "Languages",
    count: 420,
    description: "Become fluent in new languages with native speakers.",
    topics: ["English", "Spanish", "French", "Mandarin"],
  },
  {
    id: "music",
    name: "Music",
    iconName: "Music",
    count: 85,
    description: "Learn instruments, production, and music theory.",
    topics: ["Guitar", "Production", "Theory", "Piano"],
  },
  {
    id: "datascience",
    name: "Data Science",
    iconName: "Database",
    count: 110,
    description: "Analyze data, build ML models, and visualize insights.",
    topics: ["Machine Learning", "SQL", "Python", "Tableau"],
  },
  {
    id: "science",
    name: "Science",
    iconName: "FlaskConical",
    count: 95,
    description: "Explore physics, chemistry, and biology with experts.",
    topics: ["Physics", "Chemistry", "Biology", "Math"],
  },
  {
    id: "photography",
    name: "Photography",
    iconName: "Camera",
    count: 65,
    description: "Capture stunning visuals and master editing tools.",
    topics: ["Lighting", "Editing", "Portrait", "Landscape"],
  },
];
